keys:
  - &user_susagi age1g892agvnalhn7f3p5kc3l4hfjusnl947kt9g7l62wyzl2amuxyrqlcxeq7
  - &host_kiichigo age1k7y8j5vjyq692uvn70ljdztlgnlzszp9xnwdtmvk2apjucl7cdcqfh4hf5
  - &host_futro age1s2hvxx5gwn50he0u6kv97ahdvh2vcn0rrfdpgcxremj9cg9dd33q3nhl59
  - &host_naboshi age1tlvjr8hr9ph5gw4nq76whkg50ug6dt3pm232ntt6h2czknlwmuqqjlnq4g
  - &host_kyoujin age1ga4jfq3flr4qdxz93ek00a6lud7322vfgmepzvjp3e843559nu9srfg3jt
  - &host_kitsunebi age1pfnx6564wr86afyx8aczf9e4tfqsm5ddsncftqhkcv75wfupzyrqtejcsj

creation_rules:
  # nixos
  - path_regex: hosts/kitsunebi/secrets/secrets.yaml$
    key_groups:
    - age:
      - *user_susagi
      - *host_kitsunebi
  - path_regex: hosts/kiichigo/secrets/secrets.yaml$
    key_groups:
    - age:
      - *user_susagi
      - *host_kiichigo
  - path_regex: hosts/futro/secrets/secrets.yaml$
    key_groups:
    - age:
      - *user_susagi
      - *host_futro

  - path_regex: hosts/kyoujin/secrets/secrets.yaml$
    key_groups:
    - age:
      - *user_susagi
      - *host_kyoujin
  - path_regex: hosts/naboshi/secrets/secrets.yaml$
    key_groups:
    - age:
      - *user_susagi
      - *host_naboshi
  # home manager
  - path_regex: users/susagi/home/secrets/secrets.yaml$
    key_groups:
    - age:
      - *user_susagi
